// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: dataprocessor.proto

package codegen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDBSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tablename     string                 `protobuf:"bytes,1,opt,name=tablename,proto3" json:"tablename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDBSchemaRequest) Reset() {
	*x = GetDBSchemaRequest{}
	mi := &file_dataprocessor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDBSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDBSchemaRequest) ProtoMessage() {}

func (x *GetDBSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataprocessor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDBSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetDBSchemaRequest) Descriptor() ([]byte, []int) {
	return file_dataprocessor_proto_rawDescGZIP(), []int{0}
}

func (x *GetDBSchemaRequest) GetTablename() string {
	if x != nil {
		return x.Tablename
	}
	return ""
}

type GetDBSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []*ColumnInfo          `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDBSchemaResponse) Reset() {
	*x = GetDBSchemaResponse{}
	mi := &file_dataprocessor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDBSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDBSchemaResponse) ProtoMessage() {}

func (x *GetDBSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataprocessor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDBSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetDBSchemaResponse) Descriptor() ([]byte, []int) {
	return file_dataprocessor_proto_rawDescGZIP(), []int{1}
}

func (x *GetDBSchemaResponse) GetColumns() []*ColumnInfo {
	if x != nil {
		return x.Columns
	}
	return nil
}

type ColumnInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColumnName    string                 `protobuf:"bytes,1,opt,name=columnName,proto3" json:"columnName,omitempty"`
	DataType      string                 `protobuf:"bytes,2,opt,name=DataType,proto3" json:"DataType,omitempty"`
	IsNullable    string                 `protobuf:"bytes,3,opt,name=IsNullable,proto3" json:"IsNullable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnInfo) Reset() {
	*x = ColumnInfo{}
	mi := &file_dataprocessor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnInfo) ProtoMessage() {}

func (x *ColumnInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dataprocessor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnInfo.ProtoReflect.Descriptor instead.
func (*ColumnInfo) Descriptor() ([]byte, []int) {
	return file_dataprocessor_proto_rawDescGZIP(), []int{2}
}

func (x *ColumnInfo) GetColumnName() string {
	if x != nil {
		return x.ColumnName
	}
	return ""
}

func (x *ColumnInfo) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *ColumnInfo) GetIsNullable() string {
	if x != nil {
		return x.IsNullable
	}
	return ""
}

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_dataprocessor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataprocessor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_dataprocessor_proto_rawDescGZIP(), []int{3}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_dataprocessor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_dataprocessor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_dataprocessor_proto_rawDescGZIP(), []int{4}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetTransformationSuggestionsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FactTable      []*FactTable           `protobuf:"bytes,1,rep,name=fact_table,json=factTable,proto3" json:"fact_table,omitempty"`
	DimensionTable []*DimensionTable      `protobuf:"bytes,2,rep,name=dimension_table,json=dimensionTable,proto3" json:"dimension_table,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTransformationSuggestionsResponse) Reset() {
	*x = GetTransformationSuggestionsResponse{}
	mi := &file_dataprocessor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransformationSuggestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransformationSuggestionsResponse) ProtoMessage() {}

func (x *GetTransformationSuggestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataprocessor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransformationSuggestionsResponse.ProtoReflect.Descriptor instead.
func (*GetTransformationSuggestionsResponse) Descriptor() ([]byte, []int) {
	return file_dataprocessor_proto_rawDescGZIP(), []int{5}
}

func (x *GetTransformationSuggestionsResponse) GetFactTable() []*FactTable {
	if x != nil {
		return x.FactTable
	}
	return nil
}

func (x *GetTransformationSuggestionsResponse) GetDimensionTable() []*DimensionTable {
	if x != nil {
		return x.DimensionTable
	}
	return nil
}

type ForeignKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Column        []string               `protobuf:"bytes,1,rep,name=column,proto3" json:"column,omitempty"`
	References    *ForeignKey_Reference  `protobuf:"bytes,2,opt,name=references,proto3" json:"references,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForeignKey) Reset() {
	*x = ForeignKey{}
	mi := &file_dataprocessor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForeignKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForeignKey) ProtoMessage() {}

func (x *ForeignKey) ProtoReflect() protoreflect.Message {
	mi := &file_dataprocessor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForeignKey.ProtoReflect.Descriptor instead.
func (*ForeignKey) Descriptor() ([]byte, []int) {
	return file_dataprocessor_proto_rawDescGZIP(), []int{6}
}

func (x *ForeignKey) GetColumn() []string {
	if x != nil {
		return x.Column
	}
	return nil
}

func (x *ForeignKey) GetReferences() *ForeignKey_Reference {
	if x != nil {
		return x.References
	}
	return nil
}

type FactTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Columns       []*ColumnInfo          `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	PrimaryKey    []string               `protobuf:"bytes,3,rep,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	ForeignKey    []*ForeignKey          `protobuf:"bytes,4,rep,name=foreign_key,json=foreignKey,proto3" json:"foreign_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactTable) Reset() {
	*x = FactTable{}
	mi := &file_dataprocessor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactTable) ProtoMessage() {}

func (x *FactTable) ProtoReflect() protoreflect.Message {
	mi := &file_dataprocessor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactTable.ProtoReflect.Descriptor instead.
func (*FactTable) Descriptor() ([]byte, []int) {
	return file_dataprocessor_proto_rawDescGZIP(), []int{7}
}

func (x *FactTable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FactTable) GetColumns() []*ColumnInfo {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *FactTable) GetPrimaryKey() []string {
	if x != nil {
		return x.PrimaryKey
	}
	return nil
}

func (x *FactTable) GetForeignKey() []*ForeignKey {
	if x != nil {
		return x.ForeignKey
	}
	return nil
}

type DimensionTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Columns       []*ColumnInfo          `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	Primany       []string               `protobuf:"bytes,3,rep,name=primany,proto3" json:"primany,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DimensionTable) Reset() {
	*x = DimensionTable{}
	mi := &file_dataprocessor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DimensionTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DimensionTable) ProtoMessage() {}

func (x *DimensionTable) ProtoReflect() protoreflect.Message {
	mi := &file_dataprocessor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DimensionTable.ProtoReflect.Descriptor instead.
func (*DimensionTable) Descriptor() ([]byte, []int) {
	return file_dataprocessor_proto_rawDescGZIP(), []int{8}
}

func (x *DimensionTable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DimensionTable) GetColumns() []*ColumnInfo {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *DimensionTable) GetPrimany() []string {
	if x != nil {
		return x.Primany
	}
	return nil
}

type GetTransformationSuggestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrignalSchema *ColumnInfo            `protobuf:"bytes,1,opt,name=orignal_schema,json=orignalSchema,proto3" json:"orignal_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransformationSuggestionsRequest) Reset() {
	*x = GetTransformationSuggestionsRequest{}
	mi := &file_dataprocessor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransformationSuggestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransformationSuggestionsRequest) ProtoMessage() {}

func (x *GetTransformationSuggestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataprocessor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransformationSuggestionsRequest.ProtoReflect.Descriptor instead.
func (*GetTransformationSuggestionsRequest) Descriptor() ([]byte, []int) {
	return file_dataprocessor_proto_rawDescGZIP(), []int{9}
}

func (x *GetTransformationSuggestionsRequest) GetOrignalSchema() *ColumnInfo {
	if x != nil {
		return x.OrignalSchema
	}
	return nil
}

type ForeignKey_Reference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Column        []string               `protobuf:"bytes,2,rep,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForeignKey_Reference) Reset() {
	*x = ForeignKey_Reference{}
	mi := &file_dataprocessor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForeignKey_Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForeignKey_Reference) ProtoMessage() {}

func (x *ForeignKey_Reference) ProtoReflect() protoreflect.Message {
	mi := &file_dataprocessor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForeignKey_Reference.ProtoReflect.Descriptor instead.
func (*ForeignKey_Reference) Descriptor() ([]byte, []int) {
	return file_dataprocessor_proto_rawDescGZIP(), []int{6, 0}
}

func (x *ForeignKey_Reference) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *ForeignKey_Reference) GetColumn() []string {
	if x != nil {
		return x.Column
	}
	return nil
}

var File_dataprocessor_proto protoreflect.FileDescriptor

const file_dataprocessor_proto_rawDesc = "" +
	"\n" +
	"\x13dataprocessor.proto\x12\rdataprocessor\"2\n" +
	"\x12GetDBSchemaRequest\x12\x1c\n" +
	"\ttablename\x18\x01 \x01(\tR\ttablename\"J\n" +
	"\x13GetDBSchemaResponse\x123\n" +
	"\acolumns\x18\x01 \x03(\v2\x19.dataprocessor.ColumnInfoR\acolumns\"h\n" +
	"\n" +
	"ColumnInfo\x12\x1e\n" +
	"\n" +
	"columnName\x18\x01 \x01(\tR\n" +
	"columnName\x12\x1a\n" +
	"\bDataType\x18\x02 \x01(\tR\bDataType\x12\x1e\n" +
	"\n" +
	"IsNullable\x18\x03 \x01(\tR\n" +
	"IsNullable\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xa7\x01\n" +
	"$GetTransformationSuggestionsResponse\x127\n" +
	"\n" +
	"fact_table\x18\x01 \x03(\v2\x18.dataprocessor.FactTableR\tfactTable\x12F\n" +
	"\x0fdimension_table\x18\x02 \x03(\v2\x1d.dataprocessor.DimensionTableR\x0edimensionTable\"\xa4\x01\n" +
	"\n" +
	"ForeignKey\x12\x16\n" +
	"\x06column\x18\x01 \x03(\tR\x06column\x12C\n" +
	"\n" +
	"references\x18\x02 \x01(\v2#.dataprocessor.ForeignKey.ReferenceR\n" +
	"references\x1a9\n" +
	"\tReference\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x16\n" +
	"\x06column\x18\x02 \x03(\tR\x06column\"\xb1\x01\n" +
	"\tFactTable\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\acolumns\x18\x02 \x03(\v2\x19.dataprocessor.ColumnInfoR\acolumns\x12\x1f\n" +
	"\vprimary_key\x18\x03 \x03(\tR\n" +
	"primaryKey\x12:\n" +
	"\vforeign_key\x18\x04 \x03(\v2\x19.dataprocessor.ForeignKeyR\n" +
	"foreignKey\"s\n" +
	"\x0eDimensionTable\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\acolumns\x18\x02 \x03(\v2\x19.dataprocessor.ColumnInfoR\acolumns\x12\x18\n" +
	"\aprimany\x18\x03 \x03(\tR\aprimany\"g\n" +
	"#GetTransformationSuggestionsRequest\x12@\n" +
	"\x0eorignal_schema\x18\x01 \x01(\v2\x19.dataprocessor.ColumnInfoR\rorignalSchema2\xad\x01\n" +
	"\rDataprocessor\x12D\n" +
	"\bSayHello\x12\x1b.dataprocessor.HelloRequest\x1a\x19.dataprocessor.HelloReply\"\x00\x12V\n" +
	"\vGetDBSchema\x12!.dataprocessor.GetDBSchemaRequest\x1a\".dataprocessor.GetDBSchemaResponse\"\x002\x9d\x01\n" +
	"\x0fCoreTransformer\x12\x89\x01\n" +
	"\x1cGetTransformationSuggestions\x122.dataprocessor.GetTransformationSuggestionsRequest\x1a3.dataprocessor.GetTransformationSuggestionsResponse\"\x00B\n" +
	"Z\bcodegen/b\x06proto3"

var (
	file_dataprocessor_proto_rawDescOnce sync.Once
	file_dataprocessor_proto_rawDescData []byte
)

func file_dataprocessor_proto_rawDescGZIP() []byte {
	file_dataprocessor_proto_rawDescOnce.Do(func() {
		file_dataprocessor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dataprocessor_proto_rawDesc), len(file_dataprocessor_proto_rawDesc)))
	})
	return file_dataprocessor_proto_rawDescData
}

var file_dataprocessor_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_dataprocessor_proto_goTypes = []any{
	(*GetDBSchemaRequest)(nil),                   // 0: dataprocessor.GetDBSchemaRequest
	(*GetDBSchemaResponse)(nil),                  // 1: dataprocessor.GetDBSchemaResponse
	(*ColumnInfo)(nil),                           // 2: dataprocessor.ColumnInfo
	(*HelloRequest)(nil),                         // 3: dataprocessor.HelloRequest
	(*HelloReply)(nil),                           // 4: dataprocessor.HelloReply
	(*GetTransformationSuggestionsResponse)(nil), // 5: dataprocessor.GetTransformationSuggestionsResponse
	(*ForeignKey)(nil),                           // 6: dataprocessor.ForeignKey
	(*FactTable)(nil),                            // 7: dataprocessor.FactTable
	(*DimensionTable)(nil),                       // 8: dataprocessor.DimensionTable
	(*GetTransformationSuggestionsRequest)(nil),  // 9: dataprocessor.GetTransformationSuggestionsRequest
	(*ForeignKey_Reference)(nil),                 // 10: dataprocessor.ForeignKey.Reference
}
var file_dataprocessor_proto_depIdxs = []int32{
	2,  // 0: dataprocessor.GetDBSchemaResponse.columns:type_name -> dataprocessor.ColumnInfo
	7,  // 1: dataprocessor.GetTransformationSuggestionsResponse.fact_table:type_name -> dataprocessor.FactTable
	8,  // 2: dataprocessor.GetTransformationSuggestionsResponse.dimension_table:type_name -> dataprocessor.DimensionTable
	10, // 3: dataprocessor.ForeignKey.references:type_name -> dataprocessor.ForeignKey.Reference
	2,  // 4: dataprocessor.FactTable.columns:type_name -> dataprocessor.ColumnInfo
	6,  // 5: dataprocessor.FactTable.foreign_key:type_name -> dataprocessor.ForeignKey
	2,  // 6: dataprocessor.DimensionTable.columns:type_name -> dataprocessor.ColumnInfo
	2,  // 7: dataprocessor.GetTransformationSuggestionsRequest.orignal_schema:type_name -> dataprocessor.ColumnInfo
	3,  // 8: dataprocessor.Dataprocessor.SayHello:input_type -> dataprocessor.HelloRequest
	0,  // 9: dataprocessor.Dataprocessor.GetDBSchema:input_type -> dataprocessor.GetDBSchemaRequest
	9,  // 10: dataprocessor.CoreTransformer.GetTransformationSuggestions:input_type -> dataprocessor.GetTransformationSuggestionsRequest
	4,  // 11: dataprocessor.Dataprocessor.SayHello:output_type -> dataprocessor.HelloReply
	1,  // 12: dataprocessor.Dataprocessor.GetDBSchema:output_type -> dataprocessor.GetDBSchemaResponse
	5,  // 13: dataprocessor.CoreTransformer.GetTransformationSuggestions:output_type -> dataprocessor.GetTransformationSuggestionsResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_dataprocessor_proto_init() }
func file_dataprocessor_proto_init() {
	if File_dataprocessor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dataprocessor_proto_rawDesc), len(file_dataprocessor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_dataprocessor_proto_goTypes,
		DependencyIndexes: file_dataprocessor_proto_depIdxs,
		MessageInfos:      file_dataprocessor_proto_msgTypes,
	}.Build()
	File_dataprocessor_proto = out.File
	file_dataprocessor_proto_goTypes = nil
	file_dataprocessor_proto_depIdxs = nil
}
