// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: dataprocessor.proto

package codegen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Dataprocessor_SayHello_FullMethodName    = "/dataprocessor.Dataprocessor/SayHello"
	Dataprocessor_GetDBSchema_FullMethodName = "/dataprocessor.Dataprocessor/GetDBSchema"
)

// DataprocessorClient is the client API for Dataprocessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataprocessorClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	GetDBSchema(ctx context.Context, in *GetDBSchemaRequest, opts ...grpc.CallOption) (*GetDBSchemaResponse, error)
}

type dataprocessorClient struct {
	cc grpc.ClientConnInterface
}

func NewDataprocessorClient(cc grpc.ClientConnInterface) DataprocessorClient {
	return &dataprocessorClient{cc}
}

func (c *dataprocessorClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, Dataprocessor_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataprocessorClient) GetDBSchema(ctx context.Context, in *GetDBSchemaRequest, opts ...grpc.CallOption) (*GetDBSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDBSchemaResponse)
	err := c.cc.Invoke(ctx, Dataprocessor_GetDBSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataprocessorServer is the server API for Dataprocessor service.
// All implementations must embed UnimplementedDataprocessorServer
// for forward compatibility.
type DataprocessorServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	GetDBSchema(context.Context, *GetDBSchemaRequest) (*GetDBSchemaResponse, error)
	mustEmbedUnimplementedDataprocessorServer()
}

// UnimplementedDataprocessorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataprocessorServer struct{}

func (UnimplementedDataprocessorServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedDataprocessorServer) GetDBSchema(context.Context, *GetDBSchemaRequest) (*GetDBSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDBSchema not implemented")
}
func (UnimplementedDataprocessorServer) mustEmbedUnimplementedDataprocessorServer() {}
func (UnimplementedDataprocessorServer) testEmbeddedByValue()                       {}

// UnsafeDataprocessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataprocessorServer will
// result in compilation errors.
type UnsafeDataprocessorServer interface {
	mustEmbedUnimplementedDataprocessorServer()
}

func RegisterDataprocessorServer(s grpc.ServiceRegistrar, srv DataprocessorServer) {
	// If the following call pancis, it indicates UnimplementedDataprocessorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Dataprocessor_ServiceDesc, srv)
}

func _Dataprocessor_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataprocessorServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dataprocessor_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataprocessorServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dataprocessor_GetDBSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDBSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataprocessorServer).GetDBSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dataprocessor_GetDBSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataprocessorServer).GetDBSchema(ctx, req.(*GetDBSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Dataprocessor_ServiceDesc is the grpc.ServiceDesc for Dataprocessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dataprocessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dataprocessor.Dataprocessor",
	HandlerType: (*DataprocessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Dataprocessor_SayHello_Handler,
		},
		{
			MethodName: "GetDBSchema",
			Handler:    _Dataprocessor_GetDBSchema_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dataprocessor.proto",
}
